AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FileprocessAPI deployment with Lambda to launch/shutdown Windows EC2

Parameters:
  AmiId:
    Type: String
    Default: "ami-0ed981b8451912647"

  Environment:
    Type: String
    Default: "dev"
  VpcId:
    Type: String
    Default: "vpc-01335ba0a1f6a1465"
  SubnetId:
    Type: String
    Default: "subnet-0104fa10db91dc324"
  KeyName:
    Type: String
    Default: "cfn"

Globals:
  Function:
    Runtime: python3.10
    Timeout: 60
    MemorySize: 256
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  #################################
  # API Gateway
  #################################
  FileprocessApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "fileprocess-api"
      StageName: !Ref Environment
      Auth:
        ApiKeyRequired: true

  #################################
  # IAM Role + Instance Profile for EC2
  #################################
  EC2S3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "EC2S3Role-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess   
      Path: "/"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "EC2InstanceProfile-${Environment}"
      Roles:
        - !Ref EC2S3Role

  SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: !Sub "Security Group for Fileprocess Windows EC2 (${Environment})"
        VpcId: !Ref VpcId      
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 3389         
            ToPort: 3389
            CidrIp: 0.0.0.0/0      
        Tags:
          - Key: Name
            Value: !Sub "FileprocessSG-${Environment}"
  
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref KeyName
      KeyType: rsa
      Tags:
        - Key: Name
          Value: !Sub "CfnKey-${Environment}"

  #################################
  # Lambda: Create EC2 Instance
  #################################
  CreateInstanceLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "Fileprocess-Create-${Environment}"
      Description: Launch Windows EC2 instance for file processing
      Handler: process.lambda_handler
      CodeUri: ../fileprocess-api
      Environment:
        Variables:
          AMI_ID: !Ref AmiId
          INSTANCE_PROFILE_ARN: !GetAtt EC2InstanceProfile.Arn
          VPC_ID: !Ref VpcId
          SUBNET_ID: !Ref SubnetId
          SG_ID: !Ref SecurityGroup
          KEY_NAME: !Ref KeyPair
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ec2:RunInstances
                - ec2:DescribeInstances
                - iam:PassRole
              Resource: "*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /instance/create
            Method: post
            RestApiId: !Ref FileprocessApi
            Auth:
              ApiKeyRequired: true

  #################################
  # Lambda: Shutdown EC2 Instance
  #################################
  ShutdownInstanceLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "instance-terminate-${Environment}"
      Description: Shutdown  EC2 instance
      Handler: cleanup.lambda_handler
      CodeUri: ../fileprocess-api
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ec2:StopInstances
              Resource: "*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: instance/delete/{id}
            Method: get
            RestApiId: !Ref FileprocessApi
            Auth:
              ApiKeyRequired: true

  #################################
  # Save API ID in SSM
  #################################
  ApiGatewayId:
    Type: AWS::SSM::Parameter
    DependsOn: FileprocessApi
    Properties:
      Name: "/fileprocess/api/id"
      Type: String
      Value: !Ref FileprocessApi


