AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway Monitoring Backend for AWS Resources

Parameters:
  SnsTopicArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/devops-backend/authapi/id"
  CassandraHost:
    Type: String
    Default: "NONE"
    Description: Cassandra host address
  
  CassandraPort:
    Type: Number
    Description: Cassandra port number
    Default: 9042

  CassandraUsername:
    Type: String
    Default: "NONE"
    Description: Cassandra username
  
  CassandraPassword:
    Type: String
    Default: "NONE"
    Description: Cassandra password
    NoEcho: true

  Environment:
    Type: String
    Default: dev
  
  CrossAccRoleName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/ss/backend/cross-account-role-name'
  CrossAccRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/ss/backend/cross-account-role-arn'

Globals:
  Function:
    Runtime: python3.10
    Timeout: 300
    MemorySize: 256
    Environment:
      Variables:
        CASSANDRA_HOST: !Ref CassandraHost
        CASSANDRA_PORT: !Ref CassandraPort
        CASSANDRA_USER: !Ref CassandraUsername
        CASSANDRA_PASSWORD: !Ref CassandraPassword
        CASSANDRA_KEYSPACE: monitoring
        ROLE_NAME: APIGATEWAYCrossAccountMetricsRole
        USE_AWS_KEYSPACE: "false"
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "apigateway-api"
      StageName: !Ref Environment

  # 4XX Error Alarm Function
  APIGATEWAY4XXAlarmFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: Devops-apigateway_4xx_alarm_create
      Handler: apigateway_4xx_alarm_create.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - cloudwatch:*
                - ssm:*
              Resource: "*"
      Events:
        Create4XXAlarmAPI:
          Type: Api
          Properties:
            Path: /apigateway/4xx
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # 5XX Error Alarm Function
  APIGATEWAY5XXAlarmFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: Devops-apigateway_5xx_alarm_create
      Handler: apigateway_5xx_alarm_creation.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - cloudwatch:*
                - ssm:*
              Resource: "*"
      Events:
        Create5XXAlarmAPI:
          Type: Api
          Properties:
            Path: /apigateway/5xx
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # Latency Alarm Function
  APIGATEWAYLatencyAlarmFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: Devops-apigateway_latency_alarm_create
      Handler: apigateway_latency_alarm_create.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - cloudwatch:*
                - ssm:*
              Resource: "*"
      Events:
        CreateLatencyAlarmAPI:
          Type: Api
          Properties:
            Path: /apigateway/latency
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # # Health Check Function
  # APIGATEWAYHealthCheckFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: .
  #     FunctionName: Devops-apigateway_health_check
  #     Handler: health_check.lambda_handler
  #     Events:
  #       HealthCheckAPI:
  #         Type: Api
  #         Properties:
  #           Path: /health
  #           Method: get
  #           RestApiId:
  #             Ref: ApiGatewayApi

  ApiGatewayId:
    Type: AWS::SSM::Parameter
    DependsOn: ApiGatewayApi
    Properties:
      Name: "/ss/backend/apigateway-monitoring-api/id"
      Type: String
      Value: !Ref ApiGatewayApi