AWSTemplateFormatVersion: "2010-09-09"
Description: Domain configuration for Lambda Monitoring API Gateway

Parameters:
  ApiGatewayID:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/ss/backend/lambda-monitoring-api/id"
  Environment:
    Type: String
    Default: dev

  Customdomain:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/devops-backend/api/custom_domain"

Resources:
  ApiPathMappingLambda:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId:
        Ref: ApiGatewayID
      ApiMappingKey: "api/lambda"
      DomainName: !Ref Customdomain
      Stage: !Ref Environment