AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ASG Monitoring Backend for AWS Resources

Parameters:
  SnsTopicArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/devops-backend/authapi/id"
  CassandraHost:
    Type: String
    Default: "NONE"
    Description: Cassandra host address
  
  CassandraPort:
    Type: Number
    Description: Cassandra port number
    Default: 9042

  CassandraUsername:
    Type: String
    Default: "NONE"
    Description: Cassandra username
  
  CassandraPassword:
    Type: String
    Default: "NONE"
    Description: Cassandra password
    NoEcho: true

  Environment:
    Type: String
    Default: dev
  
  CrossAccRoleName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/ss/backend/cross-account-role-name'
  CrossAccRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/ss/backend/cross-account-role-arn'

Globals:
  Function:
    Runtime: python3.10
    Timeout: 300
    MemorySize: 256
    Environment:
      Variables:
        CASSANDRA_HOST: !Ref CassandraHost
        CASSANDRA_PORT: !Ref CassandraPort
        CASSANDRA_USER: !Ref CassandraUsername
        CASSANDRA_PASSWORD: !Ref CassandraPassword
        CASSANDRA_KEYSPACE: monitoring
        ROLE_NAME: ASGCrossAccountMetricsRole
        USE_AWS_KEYSPACE: "false"
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  ASGApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "asg-api"
      StageName: !Ref Environment

  # CPU Utilization Alarm Function
  ASGCPUAlarmFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: Devops-asg_cpu_alarm_create
      Handler: asg_cpu_utilization-alarm-creation.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - cloudwatch:*
                - autoscaling:*
                - ec2:*
                - ssm:*
              Resource: "*"
      Events:
        CreateCPUAlarmAPI:
          Type: Api
          Properties:
            Path: /asg/cpu
            Method: post
            RestApiId:
              Ref: ASGApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # Memory Utilization Alarm Function
  ASGMemoryAlarmFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: Devops-asg_memory_alarm_create
      Handler: asg_memory_utilization-alarm-creation.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - cloudwatch:*
                - autoscaling:*
                - ec2:*
                - ssm:*
              Resource: "*"
      Events:
        CreateMemoryAlarmAPI:
          Type: Api
          Properties:
            Path: /asg/memory
            Method: post
            RestApiId:
              Ref: ASGApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # Scaling Notification Alarm Function
  ASGScalingAlarmFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: Devops-asg_scaling_alarm_create
      Handler: asg_scaling_notification_alarm_creation.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - cloudwatch:*
                - autoscaling:*
                - ec2:*
                - ssm:*
              Resource: "*"
      Events:
        CreateScalingAlarmAPI:
          Type: Api
          Properties:
            Path: /asg/scaling
            Method: post
            RestApiId:
              Ref: ASGApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # # Health Check Function
  # ASGHealthCheckFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: .
  #     FunctionName: Devops-asg_health_check
  #     Handler: health_check.lambda_handler
  #     Events:
  #       HealthCheckAPI:
  #         Type: Api
  #         Properties:
  #           Path: /health
  #           Method: get
  #           RestApiId:
  #             Ref: ASGApi

  ASGApiId:
    Type: AWS::SSM::Parameter
    DependsOn: ASGApi
    Properties:
      Name: "/ss/backend/asg-monitoring-api/id"
      Type: String
      Value: !Ref ASGApi