AWSTemplateFormatVersion: '2010-09-09'
Description: Create ci/cd

Parameters:
  RepositoryName:
    Type: String
    Description: 'Stack Name will be used for naming'
  RepositoryBranchName:
    Type: String
  GitHubPersonalAccessToken:
    Type: String
    NoEcho: true
    Description: 'GitHub Personal Access Token for authentication'

  PipeLineName:
    Type: String
  PipelineArtifactBucket:
    Type: String
  PipelineKmsId:
    Type: String


  # CodeBuild Params
  CodeBuildSourceType:
    Type: String
    Default: 'CODEPIPELINE'
    Description: 'Type of repository to use as source (e.g., CODEPIPELINE, GITHUB, S3).'
  CodeBuildSourceLocation:
    Type: String
    Default: ''
    Description: 'GitHub Repository URL (e.g., https://github.com/username/repo)'
  CodeBuildEnvironmentType:
    Type: String
    Default: 'LINUX_CONTAINER'
    Description: 'Type of build environment (e.g., LINUX_CONTAINER, WINDOWS_CONTAINER).'
  CodeBuildArtifactsType:
    Type: String
    Default: 'CODEPIPELINE'
  CodeBuildComputeType:
    Type: String
    Default: 'BUILD_GENERAL1_SMALL'
    AllowedValues:
      - 'BUILD_GENERAL1_SMALL'
      - 'BUILD_GENERAL1_MEDIUM'
      - 'BUILD_GENERAL1_LARGE'
    Description: 'Compute type for the build (e.g., BUILD_GENERAL1_SMALL).'
  CodeBuildImage:
    Type: String
    Description: 'Standard series are ubuntu mostly'
    Default: 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'
    AllowedValues:
      - 'aws/codebuild/amazonlinux2-x86_64-standard:5.0'
      - 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'
      - 'aws/codebuild/amazonlinux2-aarch64-standard:3.0'
      - 'aws/codebuild/standard:7.0'
      - 'aws/codebuild/standard:6.0'
      - 'aws/codebuild/standard:5.0'
  CodeBuildBuildSpec:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/automation/codebuild/base/buildspec'
    Description: 'Inline commands for CodeBuild'

  CodeBuildServiceRole:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/automation/role/codebuild/Arn'
    Description: 'Access for CodeBuild'


  PipelineServiceRole:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/automation/role/pipeline/Arn'

  # Event Params
  EventServiceRole:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/automation/role/event/Arn'

Resources:
  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${PipeLineName}-Build'
      ServiceRole: !Ref CodeBuildServiceRole
      Source:
        Type: !Ref CodeBuildSourceType
        Location: !Ref CodeBuildSourceLocation
        BuildSpec: !Ref CodeBuildBuildSpec
      Environment:
        Type: !Ref CodeBuildEnvironmentType
        ComputeType: !Ref CodeBuildComputeType
        Image: !Ref CodeBuildImage
        PrivilegedMode: true
      Artifacts:
        Type: !Ref CodeBuildArtifactsType

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
      - Project
    Properties:
      Name: !Ref PipeLineName
      ArtifactStore:
        Type: 'S3'
        Location: !Ref PipelineArtifactBucket
        EncryptionKey:
          Id: !Ref PipelineKmsId
          Type: 'KMS'

      RoleArn: !Ref PipelineServiceRole
      Stages:
        - Name: "Source"
          Actions:
            - Name: "Source"
              ActionTypeId:
                Owner: 'AWS'
                Category: 'Source'
                Provider: 'GitHub'
                Version: '1'
              OutputArtifacts:
                - Name: 'SourceArtifact'
              Configuration:
                Repo: !Ref RepositoryName
                Branch: !Ref RepositoryBranchName
                OAuthToken: !Ref GitHubPersonalAccessToken  # GitHub OAuth token for authentication
                OutputArtifactFormat: 'CODE_ZIP'
                PollForSourceChanges: 'false'

              RoleArn: !Ref PipelineServiceRole
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Sub '${PipeLineName}-Build'
              RunOrder: 1
