AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  ServerlessDeploymentBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "serverless-deployment-bucket-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Name
          Value: ServerlessDeploymentBucket
        - Key: Environment
          Value: Production

  CognitoUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      UserPoolName: devops-backend-pool
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Mutable: 'false'
          Name: email
          Required: true
        - Name: scope
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: false
          StringAttributeConstraints:
            MinLength: '1'
            MaxLength: '256'
        - Name: org
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: false
          StringAttributeConstraints:
            MinLength: '1'
            MaxLength: '256'
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
        InviteMessageTemplate:
          SMSMessage: 'Your username is {username} and temporary password is {####}. '
          EmailMessage: 'Your username is {username} and temporary password is {####}. '
          EmailSubject: Your temporary password
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Priority: 1
            Name: verified_email
          - Priority: 2
            Name: verified_phone_number
      UsernameConfiguration:
        CaseSensitive: false
      VerificationMessageTemplate:
        EmailMessageByLink: >-
          Please click the link below to complete your registration. {##Verify
          Email##}
        EmailSubjectByLink: Your registration verification
        DefaultEmailOption: CONFIRM_WITH_LINK
  CognitoUserPoolClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      ClientName: devops-backend-client
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
          - USER_PASSWORD_AUTH
#        - ALLOW_ADMIN_USER_PASSWORD_AUTH
#        - ALLOW_USER_PASSWORD_AUTH
#        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false

  SsmUserPoolId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/devops-backend/userpool-id"
      Type: String
      Value: !Ref CognitoUserPool
      Description: "Cognito User Pool ID for the DevOps backend"

  SsmUserPoolClientId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/devops-backend/userpool-client-id"
      Type: String
      Value: !Ref CognitoUserPoolClient
      Description: "Cognito User Pool Client ID for the DevOps backend"



Outputs:
  ServerlessDeploymentBucketName:
    Value: !Ref ServerlessDeploymentBucket
    Export:
      Name: sls-ostrum-user-pool-test-ServerlessDeploymentBucketName
  UserPoolId:
    Value: !Ref CognitoUserPool
  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
