AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Swagger UI server via Lambda using REST API Gateway

Parameters:
  Environment:
    Type: String
    Default: dev
  LambdaLayer:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/ss/backend/client-layer-name"

Globals:
  Function:
    Runtime: python3.10
    Timeout: 60
    MemorySize: 128

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "swagger-ui"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        AllowCredentials: "'*'"
  
  SwaggerUIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub devops-swagger-ui-handler-${Environment}
      CodeUri: ../swagger-ui/         # Folder containing index.html, swagger.json, lambda_function.py
      Handler: swagger_ui.lambda_handler
      Events:
        SwaggerAPI:
          Type: Api
          Properties:
            Path: /swagger
            Method: GET
            RestApiId: !Ref ApiGatewayApi
      Policies:
        - AWSLambdaBasicExecutionRole
      Layers: 
        - !Ref LambdaLayer

  ApiGatewayId:
    Type: AWS::SSM::Parameter
    DependsOn: ApiGatewayApi
    Properties:
      Name: !Sub "/devops-backend/swagger-ui/id"
      Type: String
      Value: !Ref ApiGatewayApi
