AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Monitoring Backend for AWS Resources

Parameters:
  SnsTopicArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/devops-backend/authapi/id"
  CassandraHost:
    Type: String
    Default: "NONE"
    Description: Cassandra host address
  
  CassandraPort:
    Type: Number
    Description: Cassandra port number
    Default: 9042

  CassandraUsername:
    Type: String
    Default: "NONE"
    Description: Cassandra username
  
  CassandraPassword:
    Type: String
    Default: "NONE"
    Description: Cassandra password
    NoEcho: true

  Environment:
    Type: String
    Default: dev
    
  CrossAccRoleName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/ss/backend/cross-account-role-name'
  CrossAccRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/ss/backend/cross-account-role-arn'
    
Globals:
  Function:
    Runtime: python3.10
    Timeout: 300
    MemorySize: 256
    Environment:
      Variables:
        CASSANDRA_HOST: !Ref CassandraHost
        CASSANDRA_PORT: !Ref CassandraPort
        CASSANDRA_USER: !Ref CassandraUsername
        CASSANDRA_PASSWORD: !Ref CassandraPassword
        CASSANDRA_KEYSPACE: monitoring
        ROLE_NAME: EC2CrossAccountMetricsRole
        USE_AWS_KEYSPACE: "false"
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
Resources:
  RegionParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: '/ss/backend/region'
      Type: String
      Value: !Ref "AWS::Region"
      Description: 'AWS region the stack is deployed in'

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "ec2-api"
      StageName: !Ref Environment

  EC2CreateMonitoringFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../ec2-api
      FunctionName: Devops-ec2_monitoring_create
      Handler: ec2_monitoring_create.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - cloudwatch:*
                - ec2:DescribeInstances
                - ssm:*
                - sns:Publish
              Resource: "*"
      Events:
        InstallAPI:
          Type: Api
          Properties:
            Path: /install
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # /ec2/getMetrics
  EC2FetchMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../ec2-api
      FunctionName: Devops-ec2_fetch_metrics
      Handler: ec2_metrics_fetch.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - cloudwatch:*
                - ec2:DescribeInstances
              Resource: "*"
      Events:
        GetMetricsAPI:
          Type: Api
          Properties:
            Path: /getMetrics
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        PostMetricsAPI:
          Type: Api
          Properties:
            Path: /getMetrics
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # /ec2/getAlarms
  EC2FetchAlarmsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../ec2-api
      FunctionName: Devops-ec2_fetch_alarms
      Handler: ec2_alarms_fetch.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - cloudwatch:*
                - ec2:DescribeInstances
              Resource: "*"
      Events:
        GetAlarmsAPI:
          Type: Api
          Properties:
            Path: /getAlarms
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        PostAlarmsAPI:
          Type: Api
          Properties:
            Path: /getAlarms
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # /ec2/updateMetricsToDb
  EC2UpdateMetricsDbFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../ec2-api
      FunctionName: Devops-ec2_update_metrics_db
      Handler: ec2_monitoring-metric-db-updator.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cloudwatch:*
                - sts:AssumeRole
                - ec2:DescribeInstances
              Resource: "*"
      Events:
        UpdateMetricsToDbAPI:
          Type: Api
          Properties:
            Path: /updateMetricsToDb
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # /ec2/updateAlarmToDb
  EC2UpdateAlarmsDbFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../ec2-api
      FunctionName: Devops-ec2_update_alarm_db
      Handler: ec2_monitoring_alarm_db_updator.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cloudwatch:*
                - sts:AssumeRole
                - ec2:DescribeInstances
              Resource: "*"
      Events:
        UpdateAlarmToDbAPI:
          Type: Api
          Properties:
            Path: /updateAlarmToDb
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"
  
  ApiGatewayId:
    Type: AWS::SSM::Parameter
    DependsOn: ApiGatewayApi
    Properties:
      Name: "/devops-backend/ec2api/id"   #change
      Type: String
      Value: { Ref: ApiGatewayApi }
