AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Target Group Monitoring Backend for AWS Resources

Parameters:
  SnsTopicArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/devops-backend/authapi/id"
  CassandraHost:
    Type: String
    Default: "NONE"
    Description: Cassandra host address
  
  CassandraPort:
    Type: Number
    Description: Cassandra port number
    Default: 9042

  CassandraUsername:
    Type: String
    Default: "NONE"
    Description: Cassandra username
  
  CassandraPassword:
    Type: String
    Default: "NONE"
    Description: Cassandra password
    NoEcho: true

  Environment:
    Type: String
    Default: dev
  
  CrossAccRoleName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/ss/backend/cross-account-role-name'
  CrossAccRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/ss/backend/cross-account-role-arn'

Globals:
  Function:
    Runtime: python3.10
    Timeout: 300
    MemorySize: 256
    Environment:
      Variables:
        CASSANDRA_HOST: !Ref CassandraHost
        CASSANDRA_PORT: !Ref CassandraPort
        CASSANDRA_USER: !Ref CassandraUsername
        CASSANDRA_PASSWORD: !Ref CassandraPassword
        CASSANDRA_KEYSPACE: monitoring
        ROLE_NAME: TGCrossAccountMetricsRole
        USE_AWS_KEYSPACE: "false"
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  TGApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "tg-api"
      StageName: !Ref Environment

  # Response Time Alarm Function
  TGResponseTimeAlarmFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: Devops-tg_response_time_alarm_create
      Handler: tg_response_time_alarm_create.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - cloudwatch:*
                - elasticloadbalancing:*
                - ssm:*
              Resource: "*"
      Events:
        CreateResponseTimeAlarmAPI:
          Type: Api
          Properties:
            Path: /tg/response-time
            Method: post
            RestApiId:
              Ref: TGApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # Request Count Alarm Function
  TGRequestCountAlarmFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: Devops-tg_request_count_alarm_create
      Handler: tg_request_count_alarm_create.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - cloudwatch:*
                - elasticloadbalancing:*
                - ssm:*
              Resource: "*"
      Events:
        CreateRequestCountAlarmAPI:
          Type: Api
          Properties:
            Path: /tg/request-count
            Method: post
            RestApiId:
              Ref: TGApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # Unhealthy Host Alarm Function
  TGUnhealthyHostAlarmFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: Devops-tg_unhealthy_host_alarm_create
      Handler: tg_unhealthy_host_alarm_create.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - cloudwatch:*
                - elasticloadbalancing:*
                - ssm:*
              Resource: "*"
      Events:
        CreateUnhealthyHostAlarmAPI:
          Type: Api
          Properties:
            Path: /tg/unhealthy-hosts
            Method: post
            RestApiId:
              Ref: TGApi
      Environment:
        Variables:
          ROLE_NAME: !Ref CrossAccRoleName
          REGION: !Ref "AWS::Region"

  # Health Check Function
  # TGHealthCheckFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: .
  #     FunctionName: Devops-tg_health_check
  #     Handler: health_check.lambda_handler
  #     Events:
  #       HealthCheckAPI:
  #         Type: Api
  #         Properties:
  #           Path: /health
  #           Method: get
  #           RestApiId:
  #             # Ref: TGApi

  TGApiId:
    Type: AWS::SSM::Parameter
    DependsOn: TGApi
    Properties:
      Name: "/ss/backend/tg-monitoring-api/id"
      Type: String
      Value: !Ref TGApi 