AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deployment for Task API

Parameters:
  subneta:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /OT/VPC/SUBNET
  subnetb:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /OT/VPC/SUBNET2
  sg:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /OT/VPC/SG
  customdomain:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /OT/API/CUSTOM_DOMAIN
  UserPoolArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /OT/API/UserPoolArn
  proxyarn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /OT/VPC/proxyarn
  proxyarn1:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /OT/VPC/proxyarn1
  proxyarn2:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /OT/VPC/proxyarn2

Globals:
  Function:
    Runtime: nodejs18.x
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/mytest-lambda"
      RetentionInDays: 7

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  TestingFunction:
    Type: AWS::Serverless::Function
    Properties:
      LoggingConfig:
        LogGroup: !Ref LambdaLogGroup
      Handler: index.getLogin
      Timeout: 15
      MemorySize: 128
      FunctionName: TestingFn-inline
      Description: Testing lambda function.
      InlineCode: |
        exports.getLogin = async (event) => {
          console.log("Lambda invoked with event:", JSON.stringify(event));
          return {
            statusCode: 200,
            body: JSON.stringify({ message: "Login successful!" }),
          };
        };
      Events:
        Testing:
          Type: Api
          Properties:
            Method: get
            Path: testing/login
            RestApiId:
              Ref: ApiGatewayApi
      Policies:
        - VPCAccessPolicy: {}
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
              Resource: '*'
            - Sid: RDSConnectPolicy
              Effect: Allow
              Action:
                - rds-db:connect
              Resource:
                Fn::Sub: ${proxyarn}/*
            - Sid: RDSConnectPolicy1
              Effect: Allow
              Action:
                - rds-db:connect
              Resource:
                Fn::Sub: ${proxyarn1}/*
            - Sid: RDSConnectPolicy2
              Effect: Allow
              Action:
                - rds-db:connect
              Resource:
                Fn::Sub: ${proxyarn2}/*
      VpcConfig:
        SubnetIds:
          - !Ref subnetb
          - !Ref subneta
        SecurityGroupIds:
          - !Ref sg

  ApiGatewayId:
    Type: AWS::SSM::Parameter
    DependsOn: ApiGatewayApi
    Properties:
      Name: /OT/APIGATEWAY/TESTFUNCTION-inline/ID
      Type: String
      Value: { Ref: ApiGatewayApi }
